/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { PagedResultDto } from './dtos/PagedResultDto';
export type { IczpNet_AbpTrees_TreeInfo_1 } from './models/IczpNet_AbpTrees_TreeInfo_1';
export { IczpNet_Chat_Articles_Dtos_ArticleCreateInput } from './models/IczpNet_Chat_Articles_Dtos_ArticleCreateInput';
export { IczpNet_Chat_Articles_Dtos_ArticleDetailDto } from './models/IczpNet_Chat_Articles_Dtos_ArticleDetailDto';
export { IczpNet_Chat_Articles_Dtos_ArticleDto } from './models/IczpNet_Chat_Articles_Dtos_ArticleDto';
export { IczpNet_Chat_Articles_Dtos_ArticleUpdateInput } from './models/IczpNet_Chat_Articles_Dtos_ArticleUpdateInput';
export type { IczpNet_Chat_Cantacts_Dtos_ContactsDto } from './models/IczpNet_Chat_Cantacts_Dtos_ContactsDto';
export type { IczpNet_Chat_ChatObjectCategorys_ChatObjectCategoryInfo } from './models/IczpNet_Chat_ChatObjectCategorys_ChatObjectCategoryInfo';
export type { IczpNet_Chat_ChatObjectCategorys_Dtos_ChatObjectCategoryCreateInput } from './models/IczpNet_Chat_ChatObjectCategorys_Dtos_ChatObjectCategoryCreateInput';
export type { IczpNet_Chat_ChatObjectCategorys_Dtos_ChatObjectCategoryDetailDto } from './models/IczpNet_Chat_ChatObjectCategorys_Dtos_ChatObjectCategoryDetailDto';
export type { IczpNet_Chat_ChatObjectCategorys_Dtos_ChatObjectCategoryDto } from './models/IczpNet_Chat_ChatObjectCategorys_Dtos_ChatObjectCategoryDto';
export type { IczpNet_Chat_ChatObjectCategorys_Dtos_ChatObjectCategoryUpdateInput } from './models/IczpNet_Chat_ChatObjectCategorys_Dtos_ChatObjectCategoryUpdateInput';
export { IczpNet_Chat_ChatObjects_ChatObjectInfo } from './models/IczpNet_Chat_ChatObjects_ChatObjectInfo';
export { IczpNet_Chat_ChatObjects_Dtos_ChatObjectCreateInput } from './models/IczpNet_Chat_ChatObjects_Dtos_ChatObjectCreateInput';
export { IczpNet_Chat_ChatObjects_Dtos_ChatObjectDetailDto } from './models/IczpNet_Chat_ChatObjects_Dtos_ChatObjectDetailDto';
// export { ChatObjectDto } from './models/ChatObjectDto';
// export { ChatObjectDto } from './models/ChatObjectDto';
export type { ChatObjectUpdateInput } from './models/ChatObjectUpdateInput';
export type { IczpNet_Chat_ChatObjectTypes_Dtos_ChatObjectTypeCreateInput } from './models/IczpNet_Chat_ChatObjectTypes_Dtos_ChatObjectTypeCreateInput';
// export type { IczpNet_Chat_ChatObjectTypes_Dtos_ChatObjectTypeDetailDto } from './models/IczpNet_Chat_ChatObjectTypes_Dtos_ChatObjectTypeDetailDto';
export type { IczpNet_Chat_ChatObjectTypes_Dtos_ChatObjectTypeDto } from './models/IczpNet_Chat_ChatObjectTypes_Dtos_ChatObjectTypeDto';
export type { IczpNet_Chat_ChatObjectTypes_Dtos_ChatObjectTypeUpdateInput } from './models/IczpNet_Chat_ChatObjectTypes_Dtos_ChatObjectTypeUpdateInput';
export type { IczpNet_Chat_Connections_Dtos_ConnectionCreateInput } from './models/IczpNet_Chat_Connections_Dtos_ConnectionCreateInput';
export type { IczpNet_Chat_Connections_Dtos_ConnectionDto } from './models/IczpNet_Chat_Connections_Dtos_ConnectionDto';
export type { IczpNet_Chat_Connections_Dtos_GetOnlineCountOutput } from './models/IczpNet_Chat_Connections_Dtos_GetOnlineCountOutput';
export type { IczpNet_Chat_ContactTags_Dtos_ContactTagCreateInput } from './models/IczpNet_Chat_ContactTags_Dtos_ContactTagCreateInput';
export type { IczpNet_Chat_ContactTags_Dtos_ContactTagDetailDto } from './models/IczpNet_Chat_ContactTags_Dtos_ContactTagDetailDto';
export type { IczpNet_Chat_ContactTags_Dtos_ContactTagDto } from './models/IczpNet_Chat_ContactTags_Dtos_ContactTagDto';
export type { IczpNet_Chat_ContactTags_Dtos_ContactTagUpdateInput } from './models/IczpNet_Chat_ContactTags_Dtos_ContactTagUpdateInput';
export type { IczpNet_Chat_Dashboards_Dtos_DbTableDto } from './models/IczpNet_Chat_Dashboards_Dtos_DbTableDto';
export type { IczpNet_Chat_Developers_Dtos_DecryptOutput } from './models/IczpNet_Chat_Developers_Dtos_DecryptOutput';
export type { IczpNet_Chat_Developers_Dtos_DeveloperDto } from './models/IczpNet_Chat_Developers_Dtos_DeveloperDto';
export type { IczpNet_Chat_Developers_Dtos_EncryptInput } from './models/IczpNet_Chat_Developers_Dtos_EncryptInput';
export type { IczpNet_Chat_Developers_Dtos_EncryptOutput } from './models/IczpNet_Chat_Developers_Dtos_EncryptOutput';
export type { IczpNet_Chat_Developers_Dtos_GenerateSignatureOutput } from './models/IczpNet_Chat_Developers_Dtos_GenerateSignatureOutput';

export type { IczpNet_Chat_EntryNames_Dtos_EntryNameCreateInput } from './models/IczpNet_Chat_EntryNames_Dtos_EntryNameCreateInput';
export type { IczpNet_Chat_EntryNames_Dtos_EntryNameDetailDto } from './models/IczpNet_Chat_EntryNames_Dtos_EntryNameDetailDto';
export type { IczpNet_Chat_EntryNames_Dtos_EntryNameDto } from './models/IczpNet_Chat_EntryNames_Dtos_EntryNameDto';

export type { IczpNet_Chat_EntryNames_Dtos_EntryNameUpdateInput } from './models/IczpNet_Chat_EntryNames_Dtos_EntryNameUpdateInput';
export type { IczpNet_Chat_EntryValues_Dtos_EntryValueCreateInput } from './models/IczpNet_Chat_EntryValues_Dtos_EntryValueCreateInput';
export type { IczpNet_Chat_EntryValues_Dtos_EntryValueDetailDto } from './models/IczpNet_Chat_EntryValues_Dtos_EntryValueDetailDto';
export type { IczpNet_Chat_EntryValues_Dtos_EntryValueDto } from './models/IczpNet_Chat_EntryValues_Dtos_EntryValueDto';

export type { IczpNet_Chat_EntryValues_Dtos_EntryValueUpdateInput } from './models/IczpNet_Chat_EntryValues_Dtos_EntryValueUpdateInput';
export type { IczpNet_Chat_Enums_Dtos_EnumDto } from './models/IczpNet_Chat_Enums_Dtos_EnumDto';
export type { IczpNet_Chat_Enums_Dtos_EnumTypeDto } from './models/IczpNet_Chat_Enums_Dtos_EnumTypeDto';
export { IczpNet_Chat_FavoritedRecorders_Dtos_FavoritedRecorderDto } from './models/IczpNet_Chat_FavoritedRecorders_Dtos_FavoritedRecorderDto';
export type { IczpNet_Chat_InvitationCodes_Dtos_InvitationCodeCreateInput } from './models/IczpNet_Chat_InvitationCodes_Dtos_InvitationCodeCreateInput';
export type { IczpNet_Chat_InvitationCodes_Dtos_InvitationCodeDetailDto } from './models/IczpNet_Chat_InvitationCodes_Dtos_InvitationCodeDetailDto';
export type { IczpNet_Chat_InvitationCodes_Dtos_InvitationCodeDto } from './models/IczpNet_Chat_InvitationCodes_Dtos_InvitationCodeDto';
export type { IczpNet_Chat_InvitationCodes_Dtos_InvitationCodeUpdateInput } from './models/IczpNet_Chat_InvitationCodes_Dtos_InvitationCodeUpdateInput';
export type { IczpNet_Chat_Locations_Dto_UserLocationDto } from './models/IczpNet_Chat_Locations_Dto_UserLocationDto';
export type { IczpNet_Chat_Locations_MediaItem } from './models/IczpNet_Chat_Locations_MediaItem';
export type { IczpNet_Chat_Locations_MediaLocation } from './models/IczpNet_Chat_Locations_MediaLocation';
export type { IczpNet_Chat_Locations_ShareLocationInput } from './models/IczpNet_Chat_Locations_ShareLocationInput';
export type { IczpNet_Chat_Locations_ShareLocationOutput } from './models/IczpNet_Chat_Locations_ShareLocationOutput';
export type { IczpNet_Chat_Locations_StopShareLocationInput } from './models/IczpNet_Chat_Locations_StopShareLocationInput';
export type { IczpNet_Chat_Locations_UserLocationCacheItem } from './models/IczpNet_Chat_Locations_UserLocationCacheItem';
export type { IczpNet_Chat_Menus_Dtos_MenuCreateInput } from './models/IczpNet_Chat_Menus_Dtos_MenuCreateInput';
export type { IczpNet_Chat_Menus_Dtos_MenuDto } from './models/IczpNet_Chat_Menus_Dtos_MenuDto';
export type { IczpNet_Chat_Menus_Dtos_MenuUpdateInput } from './models/IczpNet_Chat_Menus_Dtos_MenuUpdateInput';
export type { IczpNet_Chat_Menus_MenuInfo } from './models/IczpNet_Chat_Menus_MenuInfo';
export { IczpNet_Chat_MessageSections_Messages_Dtos_MessageDto } from './models/IczpNet_Chat_MessageSections_Messages_Dtos_MessageDto';
export { IczpNet_Chat_MessageSections_Messages_Dtos_MessageFavoriteDto } from './models/IczpNet_Chat_MessageSections_Messages_Dtos_MessageFavoriteDto';
export { IczpNet_Chat_MessageSections_Messages_Dtos_MessageOwnerDto } from './models/IczpNet_Chat_MessageSections_Messages_Dtos_MessageOwnerDto';
// export { IczpNet_Chat_MessageSections_Messages_MessageInfo_1 } from './models/IczpNet_Chat_MessageSections_Messages_MessageInfo_1';

// export type { IczpNet_Chat_MessageSections_Messages_MessageInput_1 } from './models/IczpNet_Chat_MessageSections_Messages_MessageInput_1';

// export type { IczpNet_Chat_MessageSections_Templates_CmdContentInfo } from './models/IczpNet_Chat_MessageSections_Templates_CmdContentInfo';
// export { IczpNet_Chat_MessageSections_Templates_ContactsContentInfo } from './models/IczpNet_Chat_MessageSections_Templates_ContactsContentInfo';
// export type { IczpNet_Chat_MessageSections_Templates_FileContentInfo } from './models/IczpNet_Chat_MessageSections_Templates_FileContentInfo';
// export type { IczpNet_Chat_MessageSections_Templates_HistoryContentInput } from './models/IczpNet_Chat_MessageSections_Templates_HistoryContentInput';
// export type { IczpNet_Chat_MessageSections_Templates_HistoryContentOutput } from './models/IczpNet_Chat_MessageSections_Templates_HistoryContentOutput';
// export { IczpNet_Chat_MessageSections_Templates_HtmlContentInfo } from './models/IczpNet_Chat_MessageSections_Templates_HtmlContentInfo';
// export type { IczpNet_Chat_MessageSections_Templates_ImageContentInfo } from './models/IczpNet_Chat_MessageSections_Templates_ImageContentInfo';
// export type { IczpNet_Chat_MessageSections_Templates_LinkContentInfo } from './models/IczpNet_Chat_MessageSections_Templates_LinkContentInfo';
// export type { IczpNet_Chat_MessageSections_Templates_LocationContentInfo } from './models/IczpNet_Chat_MessageSections_Templates_LocationContentInfo';
// export { IczpNet_Chat_MessageSections_Templates_RedEnvelopeContentInput } from './models/IczpNet_Chat_MessageSections_Templates_RedEnvelopeContentInput';
// export { IczpNet_Chat_MessageSections_Templates_RedEnvelopeContentOutput } from './models/IczpNet_Chat_MessageSections_Templates_RedEnvelopeContentOutput';
// export type { IczpNet_Chat_MessageSections_Templates_SoundContentInfo } from './models/IczpNet_Chat_MessageSections_Templates_SoundContentInfo';
// export type { IczpNet_Chat_MessageSections_Templates_TextContentInfo } from './models/IczpNet_Chat_MessageSections_Templates_TextContentInfo';
// export type { IczpNet_Chat_MessageSections_Templates_VideoContentInfo } from './models/IczpNet_Chat_MessageSections_Templates_VideoContentInfo';
export type { IczpNet_Chat_Mottos_Dtos_MottoCreateInput } from './models/IczpNet_Chat_Mottos_Dtos_MottoCreateInput';
export type { IczpNet_Chat_Mottos_Dtos_MottoDetailDto } from './models/IczpNet_Chat_Mottos_Dtos_MottoDetailDto';
export type { IczpNet_Chat_Mottos_Dtos_MottoDto } from './models/IczpNet_Chat_Mottos_Dtos_MottoDto';
export type { IczpNet_Chat_Mottos_Dtos_MottoUpdateInput } from './models/IczpNet_Chat_Mottos_Dtos_MottoUpdateInput';
export type { IczpNet_Chat_OfficialSections_Officials_Dtos_OfficialCreateInput } from './models/IczpNet_Chat_OfficialSections_Officials_Dtos_OfficialCreateInput';
export type { IczpNet_Chat_OpenedRecorders_Dtos_OpenedRecorderDto } from './models/IczpNet_Chat_OpenedRecorders_Dtos_OpenedRecorderDto';
export type { IczpNet_Chat_Robots_Dtos_RobotCreateInput } from './models/IczpNet_Chat_Robots_Dtos_RobotCreateInput';
export { IczpNet_Chat_Robots_Dtos_RobotDto } from './models/IczpNet_Chat_Robots_Dtos_RobotDto';
export type { IczpNet_Chat_Robots_Dtos_RobotUpdateInput } from './models/IczpNet_Chat_Robots_Dtos_RobotUpdateInput';
export type { RoomCreateInput } from './models/RoomCreateInput';
export type { IczpNet_Chat_RoomSections_Rooms_InviteInput } from './models/IczpNet_Chat_RoomSections_Rooms_InviteInput';
export type { IczpNet_Chat_SessionSections_SessionOrganizations_SessionOrganizationInfo } from './models/IczpNet_Chat_SessionSections_SessionOrganizations_SessionOrganizationInfo';
export type { IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionOrganizationCreateBySessionUnitInput } from './models/IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionOrganizationCreateBySessionUnitInput';
export type { IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionOrganizationCreateInput } from './models/IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionOrganizationCreateInput';
export type { IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionOrganizationDetailDto } from './models/IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionOrganizationDetailDto';
export type { IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionOrganizationDto } from './models/IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionOrganizationDto';
export type { IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionOrganizationUpdateInput } from './models/IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionOrganizationUpdateInput';
export type { IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionPermissionGroupCreateInput } from './models/IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionPermissionGroupCreateInput';
export type { IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionPermissionGroupDetailDto } from './models/IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionPermissionGroupDetailDto';
export type { IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionPermissionGroupDto } from './models/IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionPermissionGroupDto';
export type { IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionPermissionGroupUpdateInput } from './models/IczpNet_Chat_SessionSections_SessionOrganiztions_Dtos_SessionPermissionGroupUpdateInput';
export type { SessionPermissionDefinitionDetailDto as IczpNet_Chat_SessionSections_SessionPermissionDefinitions_Dtos_SessionPermissionDefinitionDetailDto } from './models/SessionPermissionDefinitionDetailDto';
export type { IczpNet_Chat_SessionSections_SessionPermissionDefinitions_Dtos_SessionPermissionDefinitionDto } from './models/IczpNet_Chat_SessionSections_SessionPermissionDefinitions_Dtos_SessionPermissionDefinitionDto';
export type { IczpNet_Chat_SessionSections_SessionPermissionDefinitions_Dtos_SessionPermissionDefinitionUpdateInput } from './models/IczpNet_Chat_SessionSections_SessionPermissionDefinitions_Dtos_SessionPermissionDefinitionUpdateInput';
export type { IczpNet_Chat_SessionSections_SessionPermissionGroups_SessionPermissionGroupInfo } from './models/IczpNet_Chat_SessionSections_SessionPermissionGroups_SessionPermissionGroupInfo';
export type { IczpNet_Chat_SessionSections_SessionPermissions_Dtos_SessionPermissionGrantDto } from './models/IczpNet_Chat_SessionSections_SessionPermissions_Dtos_SessionPermissionGrantDto';
export type { IczpNet_Chat_SessionSections_SessionPermissions_Dtos_SessionPermissionRoleGrantDto } from './models/IczpNet_Chat_SessionSections_SessionPermissions_Dtos_SessionPermissionRoleGrantDto';
export type { IczpNet_Chat_SessionSections_SessionPermissions_Dtos_SessionPermissionUnitGrantDto } from './models/IczpNet_Chat_SessionSections_SessionPermissions_Dtos_SessionPermissionUnitGrantDto';
export type { PermissionGrantValue as IczpNet_Chat_SessionSections_SessionPermissions_PermissionGrantValue } from './models/PermissionGrantValue';
export type { SessionRequestDetailDto as IczpNet_Chat_SessionSections_SessionRequests_Dtos_SessionRequestDetailDto } from './dtos/SessionRequestDetailDto';
export type { IczpNet_Chat_SessionSections_SessionRequests_Dtos_SessionRequestDto } from './models/IczpNet_Chat_SessionSections_SessionRequests_Dtos_SessionRequestDto';
export type { SessionRoleBySessionUnitCreateInput as IczpNet_Chat_SessionSections_SessionRoles_Dtos_SessionRoleCreateBySessionUnitInput } from './models/SessionRoleBySessionUnitCreateInput';
export type { SessionRolePostInput as IczpNet_Chat_SessionSections_SessionRoles_Dtos_SessionRoleCreateInput } from './models/SessionRolePostInput';
export type { SessionRoleDetailDto as IczpNet_Chat_SessionSections_SessionRoles_Dtos_SessionRoleDetailDto } from './models/SessionRoleDetailDto';
export type { IczpNet_Chat_SessionSections_SessionRoles_Dtos_SessionRoleDto } from './models/IczpNet_Chat_SessionSections_SessionRoles_Dtos_SessionRoleDto';
export type { IczpNet_Chat_SessionSections_SessionRoles_Dtos_SessionRolePermissionDto } from './models/IczpNet_Chat_SessionSections_SessionRoles_Dtos_SessionRolePermissionDto';
export type { IczpNet_Chat_SessionSections_SessionRoles_Dtos_SessionRoleSimpleDto } from './models/IczpNet_Chat_SessionSections_SessionRoles_Dtos_SessionRoleSimpleDto';
export type { SessionRoleBySessionUnitUpdateInput as IczpNet_Chat_SessionSections_SessionRoles_Dtos_SessionRoleUpdateInput } from './models/SessionRoleBySessionUnitUpdateInput';
export type { IczpNet_Chat_SessionSections_Sessions_Dtos_SessionDetailDto } from './models/IczpNet_Chat_SessionSections_Sessions_Dtos_SessionDetailDto';
export type { IczpNet_Chat_SessionSections_Sessions_Dtos_SessionDto } from './models/IczpNet_Chat_SessionSections_Sessions_Dtos_SessionDto';
export type { IczpNet_Chat_SessionSections_SessionTags_Dtos_SessionTagCreateInput } from './models/IczpNet_Chat_SessionSections_SessionTags_Dtos_SessionTagCreateInput';
export type { IczpNet_Chat_SessionSections_SessionTags_Dtos_SessionTagDetailDto } from './models/IczpNet_Chat_SessionSections_SessionTags_Dtos_SessionTagDetailDto';
export type { IczpNet_Chat_SessionSections_SessionTags_Dtos_SessionTagDto } from './models/IczpNet_Chat_SessionSections_SessionTags_Dtos_SessionTagDto';
export type { IczpNet_Chat_SessionSections_SessionTags_SessionTagInfo } from './models/IczpNet_Chat_SessionSections_SessionTags_SessionTagInfo';
export type { IczpNet_Chat_SessionSections_SessionUnits_SessionUnitCacheItem } from './models/IczpNet_Chat_SessionSections_SessionUnits_SessionUnitCacheItem';
export type { IczpNet_Chat_SessionSections_SessionUnits_SessionUnitCounterInfo } from './models/IczpNet_Chat_SessionSections_SessionUnits_SessionUnitCounterInfo';
export type { IczpNet_Chat_SessionSections_SessionUnits_SessionUnitDisplayName } from './models/IczpNet_Chat_SessionSections_SessionUnits_SessionUnitDisplayName';
export type { IczpNet_Chat_SessionSections_SessionUnits_SessionUnitSenderInfo } from './models/IczpNet_Chat_SessionSections_SessionUnits_SessionUnitSenderInfo';

export type { IczpNet_Chat_SessionUnits_Dtos_SessionUnitDestinationDetailDto } from './models/IczpNet_Chat_SessionUnits_Dtos_SessionUnitDestinationDetailDto';
// export type { SessionUnitDestinationDto } from './SessionUnitDestinationDto';
export type { IczpNet_Chat_SessionUnits_Dtos_SessionUnitDto } from './models/IczpNet_Chat_SessionUnits_Dtos_SessionUnitDto';

export type { SessionUnitOwnerDto as SessionUnitOwnerDto } from './dtos/SessionUnitOwnerDto';
export type { IczpNet_Chat_SessionUnits_Dtos_SessionUnitSettingDto } from './models/IczpNet_Chat_SessionUnits_Dtos_SessionUnitSettingDto';
export type { IczpNet_Chat_SessionUnits_SessionUnitStatModel } from './models/IczpNet_Chat_SessionUnits_SessionUnitStatModel';
export type { IczpNet_Chat_ShopKeepers_Dtos_ShopKeeperCreateInput } from './models/IczpNet_Chat_ShopKeepers_Dtos_ShopKeeperCreateInput';
export { IczpNet_Chat_ShopKeepers_Dtos_ShopKeeperDto } from './models/IczpNet_Chat_ShopKeepers_Dtos_ShopKeeperDto';
export type { IczpNet_Chat_ShopWaiters_Dtos_ShopWaiterCreateInput } from './models/IczpNet_Chat_ShopWaiters_Dtos_ShopWaiterCreateInput';
export { IczpNet_Chat_ShopWaiters_Dtos_ShopWaiterDto } from './models/IczpNet_Chat_ShopWaiters_Dtos_ShopWaiterDto';
export type { IczpNet_Chat_ShopWaiters_Dtos_ShopWaiterUpdateInput } from './models/ShopWaiterUpdateInput';
export { IczpNet_Chat_Squares_Dtos_SquareDto } from './models/IczpNet_Chat_Squares_Dtos_SquareDto';
export type { IczpNet_Chat_WalletOrders_Dtos_WalletOrderCreateInput } from './models/IczpNet_Chat_WalletOrders_Dtos_WalletOrderCreateInput';
export { IczpNet_Chat_WalletOrders_Dtos_WalletOrderDetailDto } from './models/IczpNet_Chat_WalletOrders_Dtos_WalletOrderDetailDto';
export { IczpNet_Chat_WalletOrders_Dtos_WalletOrderDto } from './models/IczpNet_Chat_WalletOrders_Dtos_WalletOrderDto';
export type { IczpNet_Chat_WalletOrders_Dtos_WalletOrderUpdateInput } from './models/IczpNet_Chat_WalletOrders_Dtos_WalletOrderUpdateInput';
export { IczpNet_Chat_WalletRecorders_Dtos_WalletRecorderDto } from './models/IczpNet_Chat_WalletRecorders_Dtos_WalletRecorderDto';
export type { IczpNet_Chat_Wallets_Dtos_RechargeInput } from './models/IczpNet_Chat_Wallets_Dtos_RechargeInput';
export type { IczpNet_Chat_Wallets_Dtos_WalletDetailDto } from './models/IczpNet_Chat_Wallets_Dtos_WalletDetailDto';
export type { IczpNet_Chat_Wallets_Dtos_WalletDto } from './models/IczpNet_Chat_Wallets_Dtos_WalletDto';
export type { IczpNet_Chat_Words_Dtos_WordCreateInput } from './models/IczpNet_Chat_Words_Dtos_WordCreateInput';
export type { IczpNet_Chat_Words_Dtos_WordDetailDto } from './models/IczpNet_Chat_Words_Dtos_WordDetailDto';
export type { IczpNet_Chat_Words_Dtos_WordDto } from './models/IczpNet_Chat_Words_Dtos_WordDto';
export type { IczpNet_Chat_Words_Dtos_WordUpdateInput } from './models/IczpNet_Chat_Words_Dtos_WordUpdateInput';
export type { Volo_Abp_Application_Dtos_ListResultDto_1 } from './models/Volo_Abp_Application_Dtos_ListResultDto_1';

export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto';
export type { Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone } from './models/Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone';
export type { Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto } from './models/Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto';
export type { Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto } from './models/Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto';
export type { Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto } from './models/Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto';
export type { Volo_Abp_Http_Modeling_ActionApiDescriptionModel } from './models/Volo_Abp_Http_Modeling_ActionApiDescriptionModel';
export type { Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel } from './models/Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel';
export type { Volo_Abp_Http_Modeling_ControllerApiDescriptionModel } from './models/Volo_Abp_Http_Modeling_ControllerApiDescriptionModel';
export type { Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel } from './models/Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel';
export type { Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel } from './models/Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel';
export type { Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel } from './models/Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel';
export type { Volo_Abp_Http_Modeling_ModuleApiDescriptionModel } from './models/Volo_Abp_Http_Modeling_ModuleApiDescriptionModel';
export type { Volo_Abp_Http_Modeling_ParameterApiDescriptionModel } from './models/Volo_Abp_Http_Modeling_ParameterApiDescriptionModel';
export type { Volo_Abp_Http_Modeling_PropertyApiDescriptionModel } from './models/Volo_Abp_Http_Modeling_PropertyApiDescriptionModel';
export type { Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel } from './models/Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel';
export type { Volo_Abp_Http_Modeling_TypeApiDescriptionModel } from './models/Volo_Abp_Http_Modeling_TypeApiDescriptionModel';
export type { Volo_Abp_Http_RemoteServiceErrorInfo } from './models/Volo_Abp_Http_RemoteServiceErrorInfo';
export type { Volo_Abp_Http_RemoteServiceErrorResponse } from './models/Volo_Abp_Http_RemoteServiceErrorResponse';
export type { Volo_Abp_Http_RemoteServiceValidationErrorInfo } from './models/Volo_Abp_Http_RemoteServiceValidationErrorInfo';
export type { Volo_Abp_Identity_IdentityRoleCreateDto } from './models/Volo_Abp_Identity_IdentityRoleCreateDto';
export type { Volo_Abp_Identity_IdentityRoleDto } from './models/Volo_Abp_Identity_IdentityRoleDto';
export type { Volo_Abp_Identity_IdentityRoleUpdateDto } from './models/Volo_Abp_Identity_IdentityRoleUpdateDto';
export type { Volo_Abp_Identity_IdentityUserCreateDto } from './models/Volo_Abp_Identity_IdentityUserCreateDto';
export type { Volo_Abp_Identity_IdentityUserDto } from './models/Volo_Abp_Identity_IdentityUserDto';
export type { Volo_Abp_Identity_IdentityUserUpdateDto } from './models/Volo_Abp_Identity_IdentityUserUpdateDto';
export type { Volo_Abp_Identity_IdentityUserUpdateRolesDto } from './models/Volo_Abp_Identity_IdentityUserUpdateRolesDto';
export type { Volo_Abp_Localization_LanguageInfo } from './models/Volo_Abp_Localization_LanguageInfo';
export type { Volo_Abp_NameValue } from './models/Volo_Abp_NameValue';
export type { Volo_Abp_PermissionManagement_GetPermissionListResultDto } from './models/Volo_Abp_PermissionManagement_GetPermissionListResultDto';
export type { Volo_Abp_PermissionManagement_PermissionGrantInfoDto } from './models/Volo_Abp_PermissionManagement_PermissionGrantInfoDto';
export type { Volo_Abp_PermissionManagement_PermissionGroupDto } from './models/Volo_Abp_PermissionManagement_PermissionGroupDto';
export type { Volo_Abp_PermissionManagement_ProviderInfoDto } from './models/Volo_Abp_PermissionManagement_ProviderInfoDto';
export type { Volo_Abp_Users_UserData } from './models/Volo_Abp_Users_UserData';

export { AbpApiDefinitionService } from './services/AbpApiDefinitionService';
export { AbpApplicationConfigurationService } from './services/AbpApplicationConfigurationService';
export { AbpApplicationLocalizationService } from './services/AbpApplicationLocalizationService';
export { AbpTenantService } from './services/AbpTenantService';
export { ArticleService } from './services/ArticleService';
export { BlobService } from './services/BlobService';
export { CallCenterService } from './services/CallCenterService';
export { ChatObjectService } from './services/ChatObjectService';
export { ChatObjectCategoryService } from './services/ChatObjectCategoryService';
export { ChatObjectTypeService } from './services/ChatObjectTypeService';
export { ConnectionService } from './services/ConnectionService';
export { ContactsService } from './services/ContactsService';
export { ContactTagService } from './services/ContactTagService';
export { DashboardsService } from './services/DashboardsService';
export { DeveloperService } from './services/DeveloperService';
export { EntryService } from './services/EntryService';
export { EntryNameService } from './services/EntryNameService';
export { EntryValueService } from './services/EntryValueService';
export { EnumService } from './services/EnumService';
export { FavoriteService } from './services/FavoriteService';
export { FollowService } from './services/FollowService';
export { InvitationCodeService } from './services/InvitationCodeService';
export { LocationService } from './services/LocationService';
export { MenuService } from './services/MenuService';
export { MessageService } from './services/MessageService';
export { MessageSenderService } from './services/MessageSenderService';
export { MottoService } from './services/MottoService';
export { MottoAdminService } from './services/MottoAdminService';
export { OfficialService } from './services/OfficialService';
export { OpenedRecorderService } from './services/OpenedRecorderService';
export { ReadedRecorderService } from './services/ReadedRecorderService';
export { RobotService } from './services/RobotService';
export { RobotManagementService } from './services/RobotManagementService';
export { RoleService } from './services/RoleService';
export { RoomService } from './services/RoomService';
export { RoomAdminService } from './services/RoomAdminService';
export { SessionService } from './services/SessionService';
export { SessionOrganizationService } from './services/SessionOrganizationService';
export { SessionOrganiztionBySessionUnitService } from './services/SessionOrganiztionBySessionUnitService';
export { SessionPermissionService } from './services/SessionPermissionService';
export { SessionPermissionDefinitionService } from './services/SessionPermissionDefinitionService';
export { SessionPermissionGroupService } from './services/SessionPermissionGroupService';
export { SessionRequestService } from './services/SessionRequestService';
export { SessionRoleService } from './services/SessionRoleService';
export { SessionRoleBySessionUnitService } from './services/SessionRoleBySessionUnitService';
export { SessionTagService } from './services/SessionTagService';
export { SessionUnitService } from './services/SessionUnitService';
export { SettingService } from './services/SettingService';
export { ShopKeeperService } from './services/ShopKeeperService';
export { ShopWaiterService } from './services/ShopWaiterService';
export { SquareService } from './services/SquareService';
export { ToolService } from './services/ToolService';
export { UnitTestService } from './services/UnitTestService';
export { UserService } from './services/UserService';
export { UserLookupService } from './services/UserLookupService';
export { WalletService } from './services/WalletService';
export { WalletOrderService } from './services/WalletOrderService';
export { WalletRecorderService } from './services/WalletRecorderService';
export { WordService } from './services/WordService';
